### PR TITLE
remove usege-based container from controller

### PR DESCRIPTION
**Pull request by Pejdzor**
This PR is removing UsageContainer from IBM License Service.
Reason is mentioned: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63449

### CODE REVIEW

**Comment by Pejdzor** [comment]
Task: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63729

**Review by ljeda — APPROVED** [review]

**Review by kflorianski-ibm — CHANGES_REQUESTED** [review]
- Please also check `service_monitor.go` for occurrences of `ibm_licensing_usage`.
- Please check with Adam Shank if we need any changes in the CI/CD repos and link them in the issue
- Please check relevant documentation changes

**Review by kflorianski-ibm — APPROVED** [review]

**Pull request merged**
