### PR TITLE
add new sa ibm-license-service-restricted 

### PR DESCRIPTION
**Pull request by adamdyszy**
with access to pods only in chosen namespaces for operand, and new flag for this option

### CODE REVIEW

**Comment by adamdyszy** [comment]
do mot merge yet

**Review by adamdyszy — COMMENTED** [review]
all should be good now

**Review by adamdyszy — COMMENTED** [review]
now ok with hidden

**Review by kacperkrzyzak — APPROVED** [review]

**Review by kacperkrzyzak — APPROVED** [review]

**Pull request merged**
