### PR TITLE
Adopt operand digest auto-update in the operator #43681

### PR DESCRIPTION
**Pull request by SzymonKowalczyk**

### CODE REVIEW

**Comment by SzymonKowalczyk** [comment]
@horis233 thank you for assistance.

**Comment by horis233** [comment]
There was a glitch in the s390x cluster in the Prow. Now the s390x cluster is restarted and back to Prow.

**Review by adamdyszy — APPROVED** [review]

**Review by arturobrzut — APPROVED** [review]

**Pull request merged**
